[package]
name = "atuin-client"
version = "12.0.0"
authors = ["Ellie Huxtable <ellie@elliehuxtable.com>"]
edition = "2018"
license = "MIT"
description = "client library for atuin"
homepage = "https://atuin.sh"
repository = "https://github.com/ellie/atuin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sync"]
sync = [
  "urlencoding",
  "sodiumoxide",
  "reqwest",
  "sha2",
  "hex",
  "rmp-serde",
  "base64",
]

[dependencies]
atuin-common = { path = "../atuin-common", version = "12.0.0" }

log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0.18", features = ["derive"] }
eyre = "0.6"
directories = "4"
uuid = { version = "1.2", features = ["v4"] }
whoami = "1.1.2"
interim = { version = "0.1.0", features = ["chrono"] }
config = { version = "0.13", default-features = false, features = ["toml"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.92"
parse_duration = "2.1.1"
async-trait = "0.1.58"
itertools = "0.10.5"
shellexpand = "2"
sqlx = { version = "0.6", features = [
  "runtime-tokio-rustls",
  "chrono",
  "sqlite",
] }
minspan = "0.1.1"
regex = "1.5.4"
fs-err = "2.7"
sql-builder = "3"
lazy_static = "1"
memchr = "2.5"

# sync
urlencoding = { version = "2.1.0", optional = true }
sodiumoxide = { version = "0.2.6", optional = true }
reqwest = { version = "0.11", features = [
  "json",
  "rustls-tls-native-roots",
], default-features = false, optional = true }
hex = { version = "0.4", optional = true }
sha2 = { version = "0.10", optional = true }
rmp-serde = { version = "1.1.1", optional = true }
base64 = { version = "0.20.0", optional = true }
tokio = { version = "1", features = ["full"] }
semver = "1.0.14"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
