[package]
name = "atuin-client"
version = "0.8.1"
authors = ["Ellie Huxtable <ellie@elliehuxtable.com>"]
edition = "2018"
license = "MIT"
description = "client library for atuin"
homepage = "https://atuin.sh"
repository = "https://github.com/ellie/atuin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atuin-common = { path = "../atuin-common", version = "0.8.1" }

log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
eyre = "0.6"
directories = "4"
uuid = { version = "1.0", features = ["v4"] }
whoami = "1.1.2"
chrono-english = "0.1.4"
config = "0.13"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.75"
rmp-serde = "1.0.0"
sodiumoxide = "0.2.6"
reqwest = { version = "0.11", features = [
  "blocking",
  "json",
  "rustls-tls",
], default-features = false }
base64 = "0.13.0"
parse_duration = "2.1.1"
rand = "0.8.4"
rust-crypto = "^0.2"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.49"
urlencoding = "2.1.0"
itertools = "0.10.3"
shellexpand = "2"
sqlx = { version = "0.5", features = [
  "runtime-tokio-rustls",
  "uuid",
  "chrono",
  "sqlite",
] }
minspan = "0.1.1"
regex = "1.5.4"
fs-err = "2.7"
