## where to store your database, default is your system data directory
## mac: ~/Library/Application Support/com.elliehuxtable.atuin/history.db
## linux: ~/.local/share/atuin/history.db
# db_path = "~/.history.db"

## where to store your encryption key, default is your system data directory
# key_path = "~/.key"

## where to store your auth session token, default is your system data directory
# session_path = "~/.key"

## date format used, either "us" or "uk"
# dialect = "uk"

## enable or disable automatic sync
# auto_sync = true

## enable or disable automatic update checks
# update_check = true

## how often to sync history. note that this is only triggered when a command 
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
# sync_frequency = "5m"

## address of the sync server
# sync_address = "https://api.atuin.sh"

## which search mode to use
## possible values: prefix, fulltext, fuzzy
# search_mode = "prefix"

## which style to use
## possible values: auto, full, compact
#style = "auto"

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
# exit_mode = "return-original"

## possible values: emacs, subl
# word_jump_mode = "emacs"

## characters that count as a part of a word
# word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## number of context lines to show when scrolling by pages
# scroll_context_lines = 1

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+"
# ]