[package]
name = "atuin-common"
version = "0.8.0"
authors = ["Ellie Huxtable <ellie@elliehuxtable.com>"]
edition = "2018"
license = "MIT"
description = "common library for atuin"
homepage = "https://atuin.sh"
repository = "https://github.com/ellie/atuin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
sodiumoxide = "0.2.6"
chrono = { version = "0.4", features = ["serde"] }
serde_derive = "1.0.125"
serde = "1.0.126"
serde_json = "1.0.75"
warp = "0.3"
uuid = { version = "0.8", features = ["v4"] }

# eyre = "0.6"
# rmp-serde = "0.15.5"
