[package]
name = "ui"
version = "0.0.0"
description = "A Tauri App"
publish = false
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
atuin-client = { path = "../../crates/atuin-client", version = "18.4.0-beta.1" }
atuin-common = { path = "../../crates/atuin-common", version = "18.4.0-beta.1" }
atuin-dotfiles = { path = "../../crates/atuin-dotfiles", version = "0.4.0" }
atuin-history = { path = "../../crates/atuin-history", version = "0.3.0" }

eyre = "0.6"
tauri = { version = "2.0.0-beta", features = [ "tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3.36"
uuid = "1.7.0"
syntect = "5.2.0"
tauri-plugin-http = "2.0.0-beta"
tauri-plugin-single-instance = "2.0.0-beta"
tokio = "1.38.0"
tauri-plugin-shell = "2.0.0-beta.7"
comrak = "0.22"
portable-pty = "0.8.1"
vt100 = "0.15.2"
bytes = "1.6.0"
nix = "0.29.0"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.25"

[dependencies.sqlx]
version = "0.7"
features = ["runtime-tokio-rustls", "time", "postgres", "uuid"]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

#[lib]
#crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies.tauri-plugin-sql]
features = ["sqlite"]  # or "postgres", or "mysql"
version = "2.0.0-beta"
