edit_uri: /blob/main/docs/docs/
docs_dir: docs

nav:
  - Home: index.md
  - Guide:
    - Getting Started: guide/getting-started.md
    - Installation: guide/installation.md
    - Setting up sync: guide/sync.md
    - Import existing history: guide/import.md
    - Basic usage: guide/basic-usage.md
    - Syncing dotfiles: guide/dotfiles.md
    - Theming: guide/theming.md
  - Configuration:
    - Config: configuration/config.md
    - Key Binding: configuration/key-binding.md
  - Reference:
    - list: reference/list.md
    - search: reference/search.md
    - stats: reference/stats.md
    - doctor: reference/doctor.md
    - daemon: reference/daemon.md
    - import: reference/import.md
    - info: reference/info.md
    - gen-completions: reference/gen-completions.md
    - prune: reference/prune.md
    - sync: reference/sync.md
  - Self Hosting:
    - Server Setup: self-hosting/server-setup.md
    - Usage: self-hosting/usage.md
    - Docker: self-hosting/docker.md
    - Kubernetes: self-hosting/kubernetes.md
    - Systemd: self-hosting/systemd.md
  - Known Issues: known-issues.md
  - Integrations: integrations.md
  - FAQ: faq.md
  - Uninstall: uninstall.md
  - Sync v2: sync-v2.md
