[package]
name = "atuin-server"
edition = "2024"
description = "server library for atuin"

rust-version = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
argon2 = "0.5"
async-trait = { workspace = true }
atuin-common = { path = "../atuin-common", version = "18.10.0" }
atuin-server-database = { path = "../atuin-server-database", version = "18.10.0" }
axum = "0.7"
axum-server = { version = "0.7", features = ["tls-rustls"] }
config = { workspace = true }
eyre = { workspace = true }
fs-err = { workspace = true }
metrics = "0.24"
metrics-exporter-prometheus = "0.17"
postmark = { version = "0.11", features = ["reqwest", "reqwest-rustls-tls"] }
rand = { workspace = true }
reqwest = { workspace = true }
rustls = { version = "0.23" }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { version = "0.6", features = ["trace"] }

tracing = { workspace = true }
