[package]
name = "atuin-server"
edition = "2024"
description = "server library for atuin"

rust-version = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[lib]
name = "atuin_server"
path = "src/lib.rs"

[[bin]]
name = "atuin-server"
path = "src/bin/main.rs"

[dependencies]
atuin-common = { path = "../atuin-common", version = "18.13.0-beta.1" }
atuin-server-database = { path = "../atuin-server-database", version = "18.13.0-beta.1" }
atuin-server-postgres = { path = "../atuin-server-postgres", version = "18.13.0-beta.1" }
atuin-server-sqlite = { path = "../atuin-server-sqlite", version = "18.13.0-beta.1" }

tracing = { workspace = true }
time = { workspace = true }
eyre = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
axum = "0.7"
fs-err = { workspace = true }
tower = { workspace = true }
tower-http = { version = "0.6", features = ["trace"] }
reqwest = { workspace = true }
argon2 = "0.5"
semver = { workspace = true }
metrics-exporter-prometheus = { version = "0.18", default-features = false }
metrics = "0.24"
clap = { workspace = true }
tracing-subscriber = { workspace = true }
