[package]
name = "atuin-server"
edition = "2024"
description = "server library for atuin"

rust-version = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
atuin-common = { path = "../atuin-common", version = "18.11.0" }
atuin-server-database = { path = "../atuin-server-database", version = "18.11.0" }

tracing = { workspace = true }
time = { workspace = true }
eyre = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
axum = "0.7"
fs-err = { workspace = true }
tower = { workspace = true }
tower-http = { version = "0.6", features = ["trace"] }
reqwest = { workspace = true }
argon2 = "0.5"
semver = { workspace = true }
metrics-exporter-prometheus = "0.18"
metrics = "0.24"
postmark = {version= "0.11", features=["reqwest", "reqwest-rustls-tls"]}
