[package]
name = "atuin-server"
version = "12.0.0"
authors = ["Ellie Huxtable <ellie@elliehuxtable.com>"]
edition = "2018"
license = "MIT"
description = "server library for atuin"
homepage = "https://atuin.sh"
repository = "https://github.com/ellie/atuin"

[dependencies]
atuin-common = { path = "../atuin-common", version = "12.0.0" }

tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }
eyre = "0.6"
uuid = { version = "1.2", features = ["v4"] }
whoami = "1.1.2"
config = { version = "0.13", default-features = false, features = ["toml"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
sodiumoxide = "0.2.6"
base64 = "0.20.0"
rand = "0.8.4"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = [
  "runtime-tokio-rustls",
  "chrono",
  "postgres",
] }
async-trait = "0.1.58"
axum = "0.6"
http = "0.2"
fs-err = "2.7"
chronoutil = "0.2.3"
tower = "0.4"
tower-http = { version = "0.3", features = ["trace"] }
