name: build-docker

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  publish_x86:
    concurrency:
      group: ${{ github.ref }}-x86
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          repository: atuinsh/atuin
          path: "./"
          persist-credentials: false

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Login to container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Get short sha
        id: shortsha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Release build
        id: release_build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64
          file: ./Dockerfile
          context: .
          provenance: false
          build-args: |
            Version=dev
            GitCommit=${{ steps.shortsha.outputs.short_sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/atuin:${{ steps.shortsha.outputs.short_sha }}-amd64

  publish_aarch64:
    concurrency:
      group: ${{ github.ref }}-aarch64
      cancel-in-progress: true
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          repository: atuinsh/atuin
          path: "./"
          persist-credentials: false

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Login to container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Get short sha
        id: shortsha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Release build
        id: release_build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          outputs: "type=registry,push=true"
          platforms: linux/arm64
          file: ./Dockerfile
          context: .
          provenance: false
          build-args: |
            Version=dev
            GitCommit=${{ steps.shortsha.outputs.short_sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/atuin:${{ steps.shortsha.outputs.short_sha }}-aarch64

  publish_manifest:
    runs-on: ubuntu-latest
    needs: [publish_x86, publish_aarch64]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          repository: atuinsh/atuin
          path: "./"
          persist-credentials: false

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Login to container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Get short sha
        id: shortsha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create manifest
        run: |
          docker manifest create ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA} \
            --amend ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA}-amd64 \
            --amend ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA}-aarch64
          docker manifest annotate --arch amd64 --os linux ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA} ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA}-amd64
          docker manifest annotate --arch arm64 --os linux ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA} ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA}-aarch64
          docker manifest inspect ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA}

          docker manifest push ghcr.io/${REPO_OWNER}/atuin:${STEPS_SHORTSHA_OUTPUTS_SHORT_SHA}
        env:
          STEPS_SHORTSHA_OUTPUTS_SHORT_SHA: ${{ steps.shortsha.outputs.short_sha }}
